// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmlJdnH22a_RGwRczobxXAjZvyvSl-x48',
    appId: '1:235654438895:android:e53f3d88bfbe719ec9601a',
    messagingSenderId: '235654438895',
    projectId: 'zempie',
    databaseURL: 'https://zempie.firebaseio.com',
    storageBucket: 'zempie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6LGUyF36db9uc7tyWdSYaU-3S_241yY',
    appId: '1:235654438895:ios:5e15b5fcd1624be7c9601a',
    messagingSenderId: '235654438895',
    projectId: 'zempie',
    databaseURL: 'https://zempie.firebaseio.com',
    storageBucket: 'zempie.appspot.com',
    androidClientId: '235654438895-irm36ldeoqfd1sr96gpqjgsu28pcnk25.apps.googleusercontent.com',
    iosClientId: '235654438895-d6nk6ptfhrbqd9okpto2gpugmnh88v6e.apps.googleusercontent.com',
    iosBundleId: 'com.fromthered.zempie',
  );
}
